language: python
os: linux            
dist: focal
addons:
  apt:
    sources: 
      - sourceline: 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
        key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE298A3A825C0D65DFD57CBB651716619E084DAB9'
    packages:
      - r-base
    update: true
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - R --version
  - sudo R --slave -e 'install.packages("BiocManager")'
  - sudo R --slave -e 'BiocManager::install("edgeR")'
  - R -e "packageVersion('edgeR')"
install:
  - pip install -e .[test]
script:
  - python -m unittest discover -s tests/
